/*
 * File: app/view/Usuario.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Usuarios.view.Usuario', {
    extend: 'Ext.window.Window',
    alias: 'widget.usuario',

    requires: [
        'Usuarios.view.UsuarioViewModel',
        'Usuarios.view.UsuarioViewController',
        'Ext.form.Panel',
        'Ext.form.field.Number',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'usuario',
    viewModel: {
        type: 'usuario'
    },
    modal: true,
    id: 'VentanaUsuario',
    width: 400,

    items: [
        {
            xtype: 'form',
            id: 'formaCliente',
            layout: 'column',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'textfield',
                    padding: '0 0 5 0',
                    width: '100%',
                    fieldLabel: 'Nombre',
                    name: 'Nombre',
                    allowBlank: false,
                    allowOnlyWhitespace: false
                },
                {
                    xtype: 'textfield',
                    padding: '5 0 5 0',
                    width: '100%',
                    fieldLabel: 'Ap. Paterno',
                    name: 'ApPaterno',
                    allowBlank: false,
                    allowOnlyWhitespace: false
                },
                {
                    xtype: 'textfield',
                    padding: '5 0 5 0',
                    width: '100%',
                    fieldLabel: 'Ap. Materno',
                    name: 'ApMaterno',
                    allowBlank: false,
                    allowOnlyWhitespace: false
                },
                {
                    xtype: 'textfield',
                    padding: '5 0 5 0',
                    width: '100%',
                    fieldLabel: 'Teléfono',
                    name: 'Telefono',
                    allowBlank: false,
                    allowOnlyWhitespace: false
                },
                {
                    xtype: 'textfield',
                    padding: '5 0 5 0',
                    width: '100%',
                    fieldLabel: 'E-mail',
                    name: 'Correo',
                    inputType: 'email',
                    allowBlank: false,
                    allowOnlyWhitespace: false
                },
                {
                    xtype: 'textfield',
                    padding: '5 0 5 0',
                    width: '100%',
                    fieldLabel: 'Calle',
                    name: 'Calle',
                    allowBlank: false,
                    allowOnlyWhitespace: false
                },
                {
                    xtype: 'numberfield',
                    padding: '5 0 5 0',
                    width: '70%',
                    fieldLabel: 'No. Exterior',
                    name: 'NoExterior',
                    allowBlank: false,
                    allowOnlyWhitespace: false,
                    emptyText: 'No. Exterior',
                    hideTrigger: true,
                    allowDecimals: false,
                    allowExponential: false
                },
                {
                    xtype: 'textfield',
                    padding: '5 0 5 10',
                    width: '26%',
                    name: 'NoInterior',
                    emptyText: 'No. Interior'
                },
                {
                    xtype: 'textfield',
                    padding: '5 0 5 0',
                    width: '100%',
                    fieldLabel: 'Ciudad',
                    name: 'Ciudad',
                    allowBlank: false,
                    allowOnlyWhitespace: false
                },
                {
                    xtype: 'textfield',
                    padding: '5 0 5 0',
                    width: '100%',
                    fieldLabel: 'Estado',
                    name: 'Estado',
                    allowBlank: false,
                    allowOnlyWhitespace: false
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    itemId: 'BarraBotonesVU',
                    layout: {
                        type: 'hbox',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'button',
                            text: 'Cancelar',
                            listeners: {
                                click: 'onBtnCancelarClick'
                            }
                        },
                        {
                            xtype: 'button',
                            text: 'Aceptar',
                            listeners: {
                                click: 'onBtnAceptarClick'
                            }
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        show: 'onVentanaUsuarioShow'
    }

});