/*
 * File: app/view/VistaPrincipal.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Usuarios.view.VistaPrincipal', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.vistaprincipal',

    requires: [
        'Usuarios.view.VistaPrincipalViewModel',
        'Usuarios.view.VistaPrincipalViewController',
        'Ext.toolbar.Toolbar',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Spacer',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Number',
        'Ext.grid.column.Template',
        'Ext.XTemplate',
        'Ext.panel.Tool'
    ],

    controller: 'vistaprincipal',
    viewModel: {
        type: 'vistaprincipal'
    },
    height: 250,
    width: 400,
    layout: 'border',

    items: [
        {
            xtype: 'toolbar',
            region: 'north',
            id: 'BarraSuperior'
        },
        {
            xtype: 'container',
            region: 'center',
            id: 'ContenedorPrincipal',
            padding: 10,
            layout: 'border',
            items: [
                {
                    xtype: 'form',
                    region: 'center',
                    border: true,
                    id: 'FormaUsuario',
                    layout: 'border',
                    bodyPadding: 10,
                    bodyStyle: {
                        'background-color': 'white'
                    },
                    iconCls: 'x-fa fa-user',
                    title: 'Listado de usuarios',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            itemId: 'BarraBotonesVistaPrincipal',
                            layout: {
                                type: 'hbox',
                                padding: '0 5 0 5'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    reference: 'campoBusqueda',
                                    keyMapEnabled: true,
                                    width: 250,
                                    emptyText: 'Ingresa datos de filtrado',
                                    enableKeyEvents: true,
                                    listeners: {
                                        keypress: 'onTxtBusquedaKeypress',
                                        change: 'onTxtBusquedaChange'
                                    }
                                },
                                {
                                    xtype: 'combobox',
                                    reference: 'comboFiltro',
                                    editable: false,
                                    emptyText: 'Seleccionar...',
                                    displayField: 'Descripcion',
                                    store: 'Filtros'
                                },
                                {
                                    xtype: 'tbspacer',
                                    flex: 1
                                },
                                {
                                    xtype: 'button',
                                    width: 130,
                                    iconCls: 'x-fa fa-user-plus',
                                    text: 'Cliente nuevo',
                                    listeners: {
                                        click: 'onBtnAceptarCGClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    width: 130,
                                    iconCls: 'x-fa fa-pencil',
                                    text: 'Editar cliente',
                                    bind: {
                                        disabled: '{!clientesGrid.selection}'
                                    },
                                    listeners: {
                                        click: 'onBtnEditarCGClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    width: 135,
                                    iconCls: 'x-fa fa-user-times',
                                    text: 'Eliminar cliente',
                                    bind: {
                                        disabled: '{!clientesGrid.selection}'
                                    },
                                    listeners: {
                                        click: 'onBtnEliminarCGClick'
                                    }
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'gridpanel',
                            region: 'center',
                            reference: 'clientesGrid',
                            border: true,
                            id: 'clientesGrid',
                            columnLines: true,
                            store: 'Usuarios',
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'Id',
                                    text: 'ID',
                                    format: '00'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'Nombre',
                                    text: 'Nombre'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'ApellidoPaterno',
                                    text: 'Apellido Paterno'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'ApellidoMaterno',
                                    text: 'Apellido Materno'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    flex: 1,
                                    minWidth: 200,
                                    dataIndex: 'NombreCompleto',
                                    text: 'Nombre'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    minWidth: 150,
                                    dataIndex: 'Telefono',
                                    text: 'Telefono',
                                    format: '00'
                                },
                                {
                                    xtype: 'templatecolumn',
                                    flex: 1,
                                    minWidth: 200,
                                    tpl: [
                                        '<a href="mailto:{CorreoElectronico}">{CorreoElectronico}</a>'
                                    ],
                                    dataIndex: 'CorreoElectronico',
                                    text: 'E-mail'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    minWidth: 200,
                                    dataIndex: 'Calle',
                                    text: 'Calle'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    minWidth: 100,
                                    dataIndex: 'NumeroExterior',
                                    text: 'No. Exterior',
                                    format: '00'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'NumeroInterior',
                                    text: 'Numero Interior'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    minWidth: 150,
                                    dataIndex: 'Ciudad',
                                    text: 'Ciudad'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'Estado',
                                    text: 'Estado'
                                }
                            ]
                        }
                    ],
                    tools: [
                        {
                            xtype: 'tool',
                            iconCls: 'x-fa fa-refresh',
                            listeners: {
                                click: 'onToolRefreshClick'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'toolbar',
            region: 'south',
            id: 'BarraInferior'
        }
    ]

});